module.exports = [
  {
    rank: 1,
    name: 'Tommy',
    score: 55,
    longestWord: 'hijack',
    date: null,
  },
  {
    rank: 2,
    name: 'Gandalf',
    score: 47,
    longestWord: 'tepid',
    date: null,
  },
  {
    rank: 3,
    name: 'Emma',
    score: 44,
    longestWord: 'window',
    date: null,
  },
  {
    rank: 4,
    name: 'Tito',
    score: 41,
    longestWord: 'showing',
    date: null,
  },
  {
    rank: 5,
    name: 'Janet',
    score: 36,
    longestWord: 'camel',
    date: null,
  },
  {
    rank: 6,
    name: 'Michael',
    score: 33,
    longestWord: 'peppers',
    date: null,
  },
  {
    rank: 7,
    name: 'Tommy',
    score: 29,
    longestWord: 'element',
    date: null,
  },
  {
    rank: 8,
    name: 'Emma',
    score: 22,
    longestWord: 'house',
    date: null,
  },
  {
    rank: 9,
    name: 'Frodo',
    score: 19,
    longestWord: 'popped',
    date: null,
  },
  {
    rank: 10,
    name: 'Boromir',
    score: 7,
    longestWord: 'dojo',
    date: null,
  },
];